import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

import { Providers } from "@/components/providers";

import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={dmSans.className}>
        <body className="flex min-h-[calc(100vh-1px)] flex-col antialiased">
          <main className="relative flex flex-1 flex-col">
            <Providers>{children}</Providers>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
